### ISSUE TITLE
error while running 101-aks-advanced-networking/azuredeploy.json

### ISSUE THREAD

**Issue by ahmei0** [Azure/azure-quickstart-templates#8013]
resource "Microsoft.Network/virtualNetworks/subnets/providers/roleAssignments" not getting created, following error on portal

No registered resource provider found for location 'australiaeast' and API version '2015-06-15' for type 'roleAssignments'. The supported api-versions are '2014-04-01-preview, 2014-07-01-preview, 2014-10-01-preview, 2015-05-01-preview, 2015-06-01, 2015-07-01, 2016-07-01, 2017-05-01, 2017-09-01, 2017-10-01-preview, 2018-01-01-preview, 2018-07-01, 2018-09-01-preview, 2018-12-01-preview, 2019-04-01-preview, 2020-03-01-preview, 2020-04-01-preview'. The supported locations are ''. (Code: NoRegisteredProviderFound)

**Comment by ahmei0** [comment]
Hi @MCKLMT I tested it with changes you made in branch , but I still have same issue

![image](https://user-images.githubusercontent.com/62230464/91183548-f1d4fa00-e72e-11ea-87a0-d7ac4e7d6b22.png)

**Comment by MCKLMT** [comment]
The pull request has not yet been merged. The API version has well been updated to last supported version. The deployment with the CI is successful.

**Comment by ahmei0** [comment]
I know PR is not merged but I copied all the changes from your branch but still same error as in screenshot above. Do you believe changes you made should fix this issue or there is some other cause for this?

**Comment by MCKLMT** [comment]
This is strange because the API version is not the same than previously so the error message should be different. I understand why you still have the same message. Are you sure you have got the good template?

**Comment by ahmei0** [comment]
Yeah template is fine, I took from quickstart. Create vnet using prereq vnet template. Only things I changed are params

Btw API version '2015-06-15'  it reports was nowhere in template even before your changes. Not sure what it is complaining about

**Comment by ahmei0** [comment]
Please note that error above I don't see during arm deployment, nested ClusterSubnetRoleAssignmentDeployment shows successful but when I go to the resource on portal I see above error. 

My ARM deployment never ends as it gives following messages probably because of lack of permissions due to RoleAssignment not happening properly

Failed: ap-aks-vnet (Microsoft.Network/virtualNetworks)
